name: Metrics
on:
  schedule: [{ cron: "0 1 * * *" }]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          plugin_introduction: yes
          plugin_lines: no
          plugin_traffic: no

          # most used languages
          plugin_languages: yes
          plugin_languages_ignored: shaderlab, hlsl
          plugin_languages_details: percentage

          # isometric commit callendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
