name: Metrics
on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # most used languages
          plugin_languages: yes
          plugin_languages_colors: "0:orange, javascript:#ff0000, ..."
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%

          # isometric commit callendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
